eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
logging:
  level:
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
server:
  port: 8761

---
spring:
  profiles: peer-1
  application:
    name: eureka-server-clustered
server:
  port: 8761  
eureka:
  instance:
    hostname: peer-1-server.com    
  client:
    registerWithEureka: true
    fetchRegistry: true       
    serviceUrl:
      defaultZone: http://peer-2-server.com:8762/eureka/
 
---
spring:
  profiles: peer-2
  application:
    name: eureka-server-clustered   
server:
  port: 8762
eureka:
  instance:
    hostname: peer-2-server.com      
  client:
    registerWithEureka: true
    fetchRegistry: true       
    serviceUrl:
      defaultZone: http://peer-1-server.com:8761/eureka/
